import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";
import { buildReportRoster } from "../../lib/reportRoster";
import { SUBJECT_GROUPS } from "../../types";

type Question = { id:string; grade:string; subject:string; strand:string|null; sub_strand:string|null; learning_area:string|null; question_type:string; question_text:string; options:any; correct_answer:string|null; marks:number; difficulty:string|null; parts:any; };
type Note = { id:string; grade:string; subject:string; strand:string|null; sub_strand:string|null; learning_area:string|null; title:string; content:string; };

type Student={id:string;name:string;class_id:string};

export default function ExamStudio(){
 const [mode,setMode]=useState<"exam"|"notes">("exam"); const [questions,setQuestions]=useState<Question[]>([]); const [notes,setNotes]=useState<Note[]>([]); const [classes,setClasses]=useState<any[]>([]); const [students,setStudents]=useState<Student[]>([]); const [subjects,setSubjects]=useState<any[]>([]); const [teachers,setTeachers]=useState<any[]>([]); const [assignments,setAssignments]=useState<any[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const [f,setF]=useState({classId:"",grade:"",subject:"",strand:"",subStrand:"",learningArea:"",count:20,marks:30,difficulty:"mixed",personalised:true});
 const [selected,setSelected]=useState<string[]>([]); const [noteIds,setNoteIds]=useState<string[]>([]);
 useEffect(()=>{(async()=>{if(!supabase)return;const [q,c,s,l,t,a]=await Promise.all([supabase.from("question_bank").select("*").eq("active",true).order("created_at",{ascending:false}),supabase.from("classes").select("*").order("name"),supabase.from("subjects").select("*").order("name"),supabase.from("notes_bank").select("*").eq("active",true).order("created_at",{ascending:false}),supabase.from("teachers").select("*"),supabase.from("teacher_assignments").select("*")]); if(q.error) setError(q.error.message); setQuestions(q.data||[]);setClasses(c.data||[]);setSubjects(s.data||[]);setNotes(l.data||[]);setTeachers(t.data||[]);setAssignments(a.data||[]);})();},[]);
 useEffect(()=>{(async()=>{if(!supabase||!f.classId)return;const {data,error}=await supabase.from("learners").select("id,name,class_id").eq("class_id",f.classId).eq("status","active").order("name");if(error)setError(error.message);setStudents(data||[]);})();},[f.classId]);
 const grades=useMemo(()=>Array.from(new Set([...questions.map(q=>q.grade),...notes.map(n=>n.grade)].filter(Boolean))).sort(),[questions,notes]);
 const strands=useMemo(()=>Array.from(new Set((mode==="exam"?questions:notes).filter(x=>(!f.grade||x.grade===f.grade)&&(!f.subject||x.subject===f.subject)).map(x=>x.strand).filter(Boolean))).sort(),[mode,questions,notes,f.grade,f.subject]);
 const filteredQ=useMemo(()=>questions.filter(q=>(!f.grade||q.grade===f.grade)&&(!f.subject||q.subject===f.subject)&&(!f.strand||q.strand===f.strand)&&(!f.subStrand||q.sub_strand===f.subStrand)&&(!f.learningArea||q.learning_area===f.learningArea)&&(f.difficulty==="mixed"||q.difficulty===f.difficulty)),[questions,f]);
 const filteredN=useMemo(()=>notes.filter(n=>(!f.grade||n.grade===f.grade)&&(!f.subject||n.subject===f.subject)&&(!f.strand||n.strand===f.strand)&&(!f.subStrand||n.sub_strand===f.subStrand)&&(!f.learningArea||n.learning_area===f.learningArea)),[notes,f]);
 const resolvedTeacherName=useMemo(()=>{if(!f.classId||!f.subject)return"";const group=SUBJECT_GROUPS.find(g=>g.subjectNames.includes(f.subject));if(!group)return"";const roster=buildReportRoster({classId:f.classId,subjects,assignments,classTeachers:[],teachers});return roster.subjectTeacherByGroupKey[group.key]||"";},[f.classId,f.subject,subjects,assignments,teachers]);
 const pickRandom=()=>{setError("");const copy=[...filteredQ].sort(()=>Math.random()-.5);setSelected(copy.slice(0,Math.min(f.count,copy.length)).map(q=>q.id));};
 const download=async(kind:string,content:any,studentsArg:any[]=[])=>{setBusy(true);setError("");try{const {data:{session}}=await supabase!.auth.getSession(); if(!session) throw new Error("Your session has expired. Please sign in again."); const r=await fetch("/api/generate-pdf",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({kind,content,batch:studentsArg.length>1,students:studentsArg})});if(!r.ok)throw new Error(await r.text());const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=kind==="notes"?"learning-notes.pdf":kind==="scheme"?"marking-scheme.pdf":"examination.pdf";a.click();URL.revokeObjectURL(url);}catch(e:any){setError(e.message||"Generation failed")}finally{setBusy(false)}};
 const generateExam=async(kind:"exam"|"scheme")=>{const picked=questions.filter(q=>selected.includes(q.id));if(!picked.length){setError("Select questions or use Generate random questions first.");return;}const ordered=[...picked].sort((a,b)=>a.id.localeCompare(b.id));const half=Math.max(1,Math.floor(ordered.length/2));const secA=ordered.filter(q=>q.question_type==="mcq").slice(0,half);const secB=ordered.filter(q=>q.question_type!=="mcq").slice(0,half);const fallback=ordered.filter(q=>q.question_type==="mcq").length?secA:ordered.slice(0,half);const b=secB.length?secB:ordered.slice(fallback.length);const content={school:"KARIOBANGI SOUTH JUNIOR SCHOOL",subject:f.subject||ordered[0]?.subject||"",grade:f.grade||ordered[0]?.grade||"",strand:f.strand||ordered[0]?.strand||"",duration:"1 Hour",maximum_marks:fallback.reduce((s,q)=>s+Number(q.marks||1),0)+b.reduce((s,q)=>s+Number(q.marks||1),0),footer:"JUNIOR SCHOOL ASSESSMENT",student_name:"",student_class:classes.find(c=>c.id===f.classId)?.name||"",teacher:resolvedTeacherName,section_a:{marks:fallback.reduce((s,q)=>s+Number(q.marks||1),0),instructions:"Answer all questions. Choose the correct answer from A, B, C or D.",questions:fallback.map((q,i)=>({number:i+1,marks:Number(q.marks||1),text:q.question_text,options:Array.isArray(q.options)?q.options:[],answer:q.correct_answer||"A"}))},section_b:{marks:b.reduce((s,q)=>s+Number(q.marks||1),0),instructions:"Answer all questions in the spaces provided.",questions:b.map((q,i)=>({number:fallback.length+i+1,marks:Number(q.marks||1),text:q.question_text,parts:Array.isArray(q.parts)?q.parts:[{label:"a)",text:"",marks:Number(q.marks||1),answer:q.correct_answer||""}]}))}};const roster=f.personalised?students.map(s=>({name:s.name,cls:classes.find(c=>c.id===s.class_id)?.name||""})):[];await download(kind,content,roster)};
 const generateNotes=async()=>{const picked=notes.filter(n=>noteIds.includes(n.id));if(!picked.length){setError("Select at least one notes topic.");return;}await download("notes",{school:"KARIOBANGI SOUTH JUNIOR SCHOOL",title:`${f.subject||picked[0].subject} Learning Notes`,grade:f.grade||picked[0].grade,subject:f.subject||picked[0].subject,strand:f.strand,sub_strand:f.subStrand,sections:picked.map(n=>({heading:n.title,text:n.content})) ,footer:"LEARNER NOTES"},[])};
 return <div><header className="mb-6"><h1 className="font-display text-2xl text-ink">Exam & Notes Generator</h1><p className="text-sm text-ink/60 mt-1">Build material from the school's question and notes banks. JSON is created automatically for the PDF engine.</p></header>
 <div className="flex gap-2 mb-5"><button onClick={()=>setMode("exam")} className={`neu-btn ${mode!=="exam"?"opacity-50":""}`}>Examination</button><button onClick={()=>setMode("notes")} className={`neu-btn ${mode!=="notes"?"opacity-50":""}`}>Learning Notes</button></div>
 <div className="neu-card p-5 mb-5"><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
 <select className="neu-input" value={f.grade} onChange={e=>setF({...f,grade:e.target.value,strand:"",subStrand:"",learningArea:""})}><option value="">All grades</option>{grades.map(g=><option key={g}>{g}</option>)}</select>
 <select className="neu-input" value={f.subject} onChange={e=>setF({...f,subject:e.target.value,strand:"",subStrand:"",learningArea:""})}><option value="">All subjects</option>{subjects.map(s=><option key={s.id} value={s.name}>{s.name}</option>)}</select>
 <select className="neu-input" value={f.classId} onChange={e=>setF({...f,classId:e.target.value})}><option value="">Select class (for learners)</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>
 <select className="neu-input" value={f.strand} onChange={e=>setF({...f,strand:e.target.value,subStrand:"",learningArea:""})}><option value="">All strands</option>{strands.map(s=><option key={s}>{s}</option>)}</select>
 <input className="neu-input" placeholder="Sub-strand" value={f.subStrand} onChange={e=>setF({...f,subStrand:e.target.value})}/><input className="neu-input" placeholder="Learning area" value={f.learningArea} onChange={e=>setF({...f,learningArea:e.target.value})}/>
 {mode==="exam"&&<><input type="number" min="1" className="neu-input" value={f.count} onChange={e=>setF({...f,count:Number(e.target.value)})}/><select className="neu-input" value={f.difficulty} onChange={e=>setF({...f,difficulty:e.target.value})}><option value="mixed">Mixed difficulty</option><option>easy</option><option>medium</option><option>hard</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={f.personalised} onChange={e=>setF({...f,personalised:e.target.checked})}/> Put learner names on papers</label></>}
 </div></div>
 {mode==="exam"?<><div className="neu-card p-5 mb-5"><div className="flex items-center justify-between mb-3"><div><h2 className="font-display text-lg">Question Bank</h2><p className="text-xs text-ink/50">{filteredQ.length} matching question(s). Selected: {selected.length}.</p></div><button className="neu-btn" onClick={pickRandom}>Generate random questions</button></div><div className="max-h-72 overflow-auto space-y-2">{filteredQ.slice(0,200).map(q=><label key={q.id} className="block border border-line rounded p-3 text-sm"><input type="checkbox" className="mr-2" checked={selected.includes(q.id)} onChange={e=>setSelected(e.target.checked?[...selected,q.id]:selected.filter(id=>id!==q.id))}/><b>{q.subject} · {q.strand||""}</b> — {q.question_text}<span className="text-xs text-ink/40 ml-2">({q.marks} mark)</span></label>)}</div></div><div className="flex gap-2 flex-wrap"><button disabled={busy} className="neu-btn" onClick={()=>generateExam("exam")}>{busy?"Generating…":"Generate examination PDF"}</button><button disabled={busy} className="neu-btn" onClick={()=>generateExam("scheme")}>Generate marking scheme</button></div></>:<><div className="neu-card p-5 mb-5"><div className="flex items-center justify-between mb-3"><div><h2 className="font-display text-lg">Notes Bank</h2><p className="text-xs text-ink/50">{filteredN.length} matching note topic(s).</p></div></div><div className="space-y-2">{filteredN.map(n=><label key={n.id} className="block border border-line rounded p-3 text-sm"><input type="checkbox" className="mr-2" checked={noteIds.includes(n.id)} onChange={e=>setNoteIds(e.target.checked?[...noteIds,n.id]:noteIds.filter(id=>id!==n.id))}/><b>{n.title}</b><div className="text-xs text-ink/50 mt-1">{n.grade} · {n.subject} · {n.strand||""}</div></label>)}</div></div><button disabled={busy} className="neu-btn" onClick={generateNotes}>{busy?"Generating…":"Generate notes PDF"}</button></>}
 {error&&<div className="text-sm text-maroon mt-4 bg-maroon/10 border border-maroon/20 rounded p-3">{error}</div>}
 {mode==="exam"&&f.personalised&&f.classId&&<p className="text-xs text-ink/50 mt-4">{students.length} active learner(s) found in the selected class. A personalised paper will be created for each learner in one combined PDF.</p>}
 {mode==="exam"&&f.classId&&f.subject&&<p className="text-xs text-ink/50 mt-1">Teacher printed on the paper: <b>{resolvedTeacherName||"— not assigned in Learning Areas / Teacher Assignments —"}</b></p>}
 </div>;
}
